var profile = {
	"data": {
		"recentActivities": [],
		"userIdeas": [],
		"info": {
			"myProfile": true,
			"userInfo": {
				"bioDetails": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"userName": "ajohnson007",
				"userId": 14,
				"avatar": 0,
				"firstName": "Alisha",
				"middleName": "",
				"lastName": "Johnson",
				"email": "ajohnson007@example.com",
				"city": "",
				"state": "",
				"country": "",
				"imId": "",
				"voteCount": 0,
				"watchIdeaList": [],
				"watchUserList": [],
				"watchReviewList": [],
				"watchBlogList": [],
				"buddyList": [],
				"buddyInvitationList": [],
				"buddyInvitationRequestList": [],
				"peopleList": [
					{
						"firstname":"Alex Russel",
						"userId": 100,
						"avatarPath": "../../resources/images/avatar-sm-person1.png",
						"creationDate":"07/12/2012"
					},
					{
						"firstname":"Sarah Jones",
						"userId": 101,
						"avatarPath": "../../resources/images/avatar-sm-person2.png",
						"creationDate":"07/12/2012"
					}
				],
				"ideaList": [
					{
						"userName": "JasonJohnson",
						"ideaTitle": "Surfing with sharks, yay baby!!",
						"time":"2 days ago",
						"date":"13/20/2012",
						"ideaURL": "/Page/ViewIdea?ideaid\u003d1250",
						"ideaId": 1250,
						"avatarPath": "../../resources/images/profile-avatar2.png"
					},
					{
						"userName": "Sandy007",
						"ideaTitle": "Turn off the lights at night",
						"time":"14 mins ago",
						"date":"04/20/2012",
						"ideaURL": "/Page/ViewIdea?ideaid\u003d1250",
						"ideaId": 1250,
						"avatarPath": "../../resources/images/avatar-med-icon.png"
					},
					{
						"userName": "Sandy007",
						"ideaTitle": "Decorating with snowflake decals",
						"time":"2 days ago",
						"date":"04/20/2012",
						"ideaURL": "/Page/ViewIdea?ideaid\u003d1250",
						"ideaId": 1250,
						"avatarPath": "../../resources/images/avatar-sm-beach.png"
					},
					{
						"userName": "Sandy007",
						"ideaTitle": "The flowercup challenge 2012!",
						"time":"2 days ago",
						"date":"04/20/2012",
						"ideaURL": "/Page/ViewIdea?ideaid\u003d1250",
						"ideaId": 1250,
						"avatarPath": "../../resources/images/avatar-sm-light.png"
					},
					{
						"userName": "Sandy007",
						"ideaTitle": "The flowercup challenge 2012!",
						"time":"2 days ago",
						"date":"04/20/2012",
						"ideaURL": "/Page/ViewIdea?ideaid\u003d1250",
						"ideaId": 1250,
						"avatarPath": "../../resources/images/avatar-sm-person2.png"
					},
					{
						"userName": "Sandy007",
						"ideaTitle": "The flowercup challenge 2012!",
						"time":"2 days ago",
						"date":"04/20/2012",
						"ideaURL": "/Page/ViewIdea?ideaid\u003d1250",
						"ideaId": 1250,
						"avatarPath": "../../resources/images/profile-avatar.png"
					},
					{
						"userName": "Sandy007",
						"ideaTitle": "The flowercup challenge 2012!",
						"time":"2 days ago",
						"date":"04/20/2012",
						"ideaURL": "/Page/ViewIdea?ideaid\u003d1250",
						"ideaId": 1250,
						"avatarPath": "../../resources/images/avatar-sm-light.png"
					}
				],
				"watchSectorList": [],
				"recentActivity": [],
				"buddyActivity": [],
				"testimonials": [],
				"spigits": 0,
				"posts": 0,
				"ratingVotes": 0,
				"ratingTotal": 0,
				"phone": "1-(555) 321-5555",
				"fax": "",
				"website": "",
				"address1": "888 Oakshire Farms, Everglades Hill, FL 34579",
				"address2": "",
				"zip": "",
				"signature": "",
				"mobile": "",
				"tags": "",
				"avatarPath": "../../resources/images/profile-avatar.png",
				"onWatch": false,
				"isExpert": false,
				"birthday": 0,
				"company": "Spigit.com",
				"department": "",
				"jobTitle": "Javascripter",
				"hidejobTitle": false,
				"isDisabled": false,
				"profileTag": "",
				"isLocked": false,
				"isAdmin": false,
				"fullName": "",
				"userPref": {
					"isShowEmail": true,
					"isShowProfile": true,
					"isAllowChat": true,
					"isAllowIM": false,
					"allowIM": 0,
					"isAllowSendSpecialOffer": true,
					"isAllowSendUpdate": true,
					"showOnline": 1,
					"IMId": "",
					"userLocale": "en_US",
					"autotranslang": "",
					"userId": 0,
					"filterChallengeIdeas": false,
					"donotShowSplashScreen": false,
					"commentsortorder": 2
				},
				"rolesAsString": "Member",
				"joinDate": "",
				"isMember": false,
				"isSuperAdmin": false,
				"groupId": 0,
				"attributes": {}
			},
			"userPrefInfo": {
				"isShowEmail": true,
				"isShowProfile": true,
				"isAllowChat": true,
				"isAllowIM": false,
				"allowIM": 0,
				"isAllowSendSpecialOffer": false,
				"isAllowSendUpdate": true,
				"showOnline": 1,
				"IMId": "",
				"userLocale": "orig",
				"autotranslang": "orig",
				"userId": 14,
				"filterChallengeIdeas": false,
				"donotShowSplashScreen": false,
				"commentsortorder": 2
			},
			"userStat": {
				"name": "Alisha Johnson",
				"joinDate": "08/15/2012",
				"posts": 170,
				"pageViews": 18,
				"availSpigits": 25000,
				"netWorth": 10,
				"numIdeas": 230
			},
			"displayName": "Alisha Johnson",
			"doNotShowProfile": "Profile for Alisha Johnson is locked.",
			"owner": true,
			"admin": false,
			"siteMember": true,
			"accountDeactivated": false,
			"userBlogUrl": "/Page/ViewBlog?userid\u003d14",
			"showProfile": true,
			"hasAvatar": true,
			"profileURL": "/Page/UserProfile?userid\u003d14",
			"avatarPath": "../../resources/images/profile-avatar.png",
			"pAvatarLink": "",
			"editProfileAsSuURL": "/Page/EditProfile?su\u003d1\u0026userid\u003d14",
			"showPreferredNameOnProfile": false,
			"showUserEmailOnProfile": false,
			"emailChunks": ["ajohnson007@example.", "com"],
			"showUserBadges": false,
			"showReputationBadges": true,
			"showInvite": true,
			"showFullResume": false,
			"showEmail": false,
			"showTestimonials": false,
			"showWatch": false,
			"showUserProfileBlock": false,
			"userProfileBlock": "",
			"showUserAttributes": false,
			"attributes": {},
			"showBiography": true,
			"viewProfileURL": "/Page/UserProfile?userid\u003d14",
			"userReferrerLevel": "",
			"backgroundURL": "/User/ViewBackground?userid\u003d14",
			"inviteConnectionsURL": "/User/InviteConnections",
			"emailUserURL": "/User/EmailUser?userid\u003d14\u0026form_id\u003dnull\u0026prevent_formid_popup\u003dtrue",
			"postTestimonialURL": "/User/PostTestimonial?userid\u003d14",
			"onWatch": false,
			"editBackgroundURL": "/User/EditBackground?userid\u003d14",
			"workInfoList": [],
			"educationInfoList": [],
			"connected": false
		}
	},
	"success": true
};